apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dotnet-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/admbmg/sample-apps.git
    targetRevision: HEAD
    path: dotnet-api/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-dotnet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
