apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-hello
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/admbmg/sample-apps.git
    targetRevision: HEAD
    path: nginx-hello
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
